# CMake generated Testfile for 
# Source directory: /home/runner/work/miniexpr/miniexpr/tests
# Build directory: /home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_all_types "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_all_types")
set_tests_properties(test_all_types PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_auto_dtype "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_auto_dtype")
set_tests_properties(test_auto_dtype PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_basic "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_basic")
set_tests_properties(test_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_bool_output "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_bool_output")
set_tests_properties(test_bool_output PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_chunked_eval "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_chunked_eval")
set_tests_properties(test_chunked_eval PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_comparison_power "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_comparison_power")
set_tests_properties(test_comparison_power PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_complex_functions "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_complex_functions")
set_tests_properties(test_complex_functions PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_dsl_syntax "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_dsl_syntax")
set_tests_properties(test_dsl_syntax PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_dsl_udf "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_dsl_udf")
set_tests_properties(test_dsl_udf PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_dtype_validation "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_dtype_validation")
set_tests_properties(test_dtype_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_explicit_output "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_explicit_output")
set_tests_properties(test_explicit_output PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_function_order "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_function_order")
set_tests_properties(test_function_order PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_inverse_hyperbolic "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_inverse_hyperbolic")
set_tests_properties(test_inverse_hyperbolic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_inverse_trig_aliases "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_inverse_trig_aliases")
set_tests_properties(test_inverse_trig_aliases PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_mixed_types "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_mixed_types")
set_tests_properties(test_mixed_types PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_nd "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_nd")
set_tests_properties(test_nd PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_numpy_functions "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_numpy_functions")
set_tests_properties(test_numpy_functions PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_operators "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_operators")
set_tests_properties(test_operators PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_print "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_print")
set_tests_properties(test_print PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_reductions "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_reductions")
set_tests_properties(test_reductions PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_regressions "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_regressions")
set_tests_properties(test_regressions PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_simd_math "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_simd_math")
set_tests_properties(test_simd_math PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_string_ops "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_string_ops")
set_tests_properties(test_string_ops PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_threadsafe_chunk "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_threadsafe_chunk")
set_tests_properties(test_threadsafe_chunk PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_trig "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_trig")
set_tests_properties(test_trig PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
add_test(test_two_param_functions "/home/runner/work/miniexpr/miniexpr/_codeql_build_dir/tests/test_two_param_functions")
set_tests_properties(test_two_param_functions PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;16;add_test;/home/runner/work/miniexpr/miniexpr/tests/CMakeLists.txt;0;")
