#!/usr/bin/env python3
"""Regenerate src/unicode_case_table.h from the running Python's Unicode data.

miniexpr matches NumPy's case mapping, which is Python's full mapping: most
codepoints map 1:1, but a handful expand (U+00DF eszett -> "SS").  The simple
1:1 pairs and the rare expanding ones are emitted as separate tables so the
common path stays a binary search over 8-byte entries.

Usage:  python3 scripts/gen_unicode_case.py > src/unicode_case_table.h
"""

import sys
import unicodedata

MAX_CP = 0x110000


def build(attr):
    simple = []   # (from, to)
    expand = []   # (from, [cp, ...])
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:  # surrogates are not valid scalars
            continue
        src = chr(cp)
        dst = getattr(src, attr)()
        if dst == src:
            continue
        if len(dst) == 1:
            simple.append((cp, ord(dst)))
        else:
            expand.append((cp, [ord(c) for c in dst]))
    return simple, expand


def emit_simple(name, pairs):
    print(f"static const me_case_pair {name}[] = {{")
    for frm, to in pairs:
        print(f"    {{0x{frm:04X}, 0x{to:04X}}},")
    print("};")
    print(f"#define {name.upper()}_COUNT ((int)(sizeof({name}) / sizeof({name}[0])))")
    print()


def emit_expand(name, entries, maxlen):
    print(f"static const me_case_expansion {name}[] = {{")
    for frm, cps in entries:
        pad = cps + [0] * (maxlen - len(cps))
        body = ", ".join(f"0x{c:04X}" for c in pad)
        print(f"    {{0x{frm:04X}, {len(cps)}, {{{body}}}}},")
    print("};")
    print(f"#define {name.upper()}_COUNT ((int)(sizeof({name}) / sizeof({name}[0])))")
    print()


def main():
    lo_simple, lo_expand = build("lower")
    up_simple, up_expand = build("upper")

    max_lower = max((len(c) for _, c in lo_expand), default=1)
    max_upper = max((len(c) for _, c in up_expand), default=1)
    maxlen = max(max_lower, max_upper, 1)

    print("/* Generated by scripts/gen_unicode_case.py -- do not edit by hand. */")
    print(f"/* Unicode {unicodedata.unidata_version}, "
          f"Python {sys.version_info.major}.{sys.version_info.minor} */")
    print()
    print("#ifndef MINIEXPR_UNICODE_CASE_TABLE_H")
    print("#define MINIEXPR_UNICODE_CASE_TABLE_H")
    print()
    print("#include <stdint.h>")
    print()
    print(f"#define ME_CASE_MAX_EXPANSION {maxlen}")
    print()
    print("typedef struct { uint32_t from; uint32_t to; } me_case_pair;")
    print("typedef struct { uint32_t from; uint8_t len; "
          "uint32_t to[ME_CASE_MAX_EXPANSION]; } me_case_expansion;")
    print()
    emit_simple("me_case_lower_simple", lo_simple)
    emit_simple("me_case_upper_simple", up_simple)
    emit_expand("me_case_lower_expand", lo_expand, maxlen)
    emit_expand("me_case_upper_expand", up_expand, maxlen)
    print("#endif /* MINIEXPR_UNICODE_CASE_TABLE_H */")


if __name__ == "__main__":
    main()
